# Generated by Django 6.0.1 on 2026-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('shop', 'Shop Page')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('background_image', models.ImageField(upload_to='page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
