# Generated by Django 6.0.1 on 2026-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pageheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(max_length=200)),
                ('vision_text', models.TextField()),
                ('mission_title', models.CharField(max_length=200)),
                ('mission_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutWhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image_front', models.ImageField(upload_to='about/')),
                ('image_back', models.ImageField(upload_to='about/')),
                ('button_text', models.CharField(default='View Our News', max_length=100)),
                ('button_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='team/')),
                ('description', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Customer', max_length=100)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('message', models.TextField()),
            ],
        ),
    ]
