# Generated by Django 6.0.1 on 2026-01-30 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutvisionmission_aboutwhoweare_brand_teammember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=200)),
                ('header_subtitle', models.CharField(max_length=200)),
                ('header_background', models.ImageField(upload_to='about/header/')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField()),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField()),
                ('who_title', models.CharField(max_length=100)),
                ('who_subtitle', models.CharField(max_length=200)),
                ('who_description', models.TextField()),
                ('who_button_text', models.CharField(max_length=50)),
                ('who_button_url', models.URLField()),
                ('who_image_front', models.ImageField(upload_to='about/who/')),
                ('who_image_back', models.ImageField(upload_to='about/who/')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.DeleteModel(
            name='AboutVisionMission',
        ),
        migrations.DeleteModel(
            name='AboutWhoWeAre',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='about_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='website.aboutpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='about_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='website.aboutpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='about_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='website.aboutpage'),
            preserve_default=False,
        ),
    ]
