# Generated by Django 6.0.1 on 2026-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='sunday_label',
            field=models.CharField(default='Sunday', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='sunday_time',
            field=models.CharField(default='11am - 6pm ET', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='weekday_label',
            field=models.CharField(default='Monday - Saturday', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='weekday_time',
            field=models.CharField(default='11am - 7pm ET', max_length=100),
        ),
    ]
