# Generated by Django 6.0.1 on 2026-01-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_websitesettings_sunday_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('weekday_timing', models.CharField(help_text='Example: Monday - Saturday 11am to 7pm', max_length=100)),
                ('weekend_timing', models.CharField(blank=True, help_text='Example: Sunday 11am to 6pm / Closed', max_length=100)),
                ('image', models.ImageField(upload_to='stores/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store Location',
                'verbose_name_plural': 'Store Locations',
            },
        ),
    ]
