# Generated by Django 6.0.1 on 2026-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_storelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageheader',
            name='page',
            field=models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('shop', 'Shop Page'), ('team', 'Team Page')], max_length=50, unique=True),
        ),
    ]
