# Generated by Django 6.0.1 on 2026-01-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Working for the Community', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Short description about social / community work')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Community Section',
                'verbose_name_plural': 'Community Section',
            },
        ),
        migrations.CreateModel(
            name='CommunityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='community/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.communitysection')),
            ],
            options={
                'verbose_name': 'Community Image',
                'verbose_name_plural': 'Community Images',
                'ordering': ['position'],
            },
        ),
    ]
