# Generated by Django 6.0.1 on 2026-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_communitysection_communitygallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeDealerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='home/become_dealer/')),
                ('button_text', models.CharField(default='Become a Dealer', max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Become a Dealer Section',
                'verbose_name_plural': 'Become a Dealer Section',
            },
        ),
    ]
