# Generated by Django 6.0.1 on 2026-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show this category on Home → Recent Arrivals'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
