# Generated by Django 6.0.1 on 2026-01-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_product_hover_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='whatsapp_qr',
            field=models.ImageField(blank=True, help_text='Upload WhatsApp QR Code (PNG/JPG)', null=True, upload_to='site/qr/'),
        ),
    ]
