# Generated by Django 5.2.8 on 2026-05-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_websitesettings_whatsapp_qr"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurRatesSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_buy_formula_operator",
                    models.CharField(
                        choices=[
                            ("+", "Addition (+)"),
                            ("-", "Subtraction (-)"),
                            ("*", "Multiply (*)"),
                            ("/", "Divide (/)"),
                            ("%", "Percentage Markup (%)"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Gold buy formula",
                    ),
                ),
                (
                    "gold_buy_formula_value",
                    models.FloatField(
                        default=0.0, verbose_name="Gold buy formula value"
                    ),
                ),
                (
                    "gold_sell_formula_operator",
                    models.CharField(
                        choices=[
                            ("+", "Addition (+)"),
                            ("-", "Subtraction (-)"),
                            ("*", "Multiply (*)"),
                            ("/", "Divide (/)"),
                            ("%", "Percentage Markup (%)"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Gold sell formula",
                    ),
                ),
                (
                    "gold_sell_formula_value",
                    models.FloatField(
                        default=0.0, verbose_name="Gold sell formula value"
                    ),
                ),
                (
                    "silver_buy_formula_operator",
                    models.CharField(
                        choices=[
                            ("+", "Addition (+)"),
                            ("-", "Subtraction (-)"),
                            ("*", "Multiply (*)"),
                            ("/", "Divide (/)"),
                            ("%", "Percentage Markup (%)"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Silver buy formula",
                    ),
                ),
                (
                    "silver_buy_formula_value",
                    models.FloatField(
                        default=0.0, verbose_name="Silver buy formula value"
                    ),
                ),
                (
                    "silver_sell_formula_operator",
                    models.CharField(
                        choices=[
                            ("+", "Addition (+)"),
                            ("-", "Subtraction (-)"),
                            ("*", "Multiply (*)"),
                            ("/", "Divide (/)"),
                            ("%", "Percentage Markup (%)"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Silver sell formula",
                    ),
                ),
                (
                    "silver_sell_formula_value",
                    models.FloatField(
                        default=0.0, verbose_name="Silver sell formula value"
                    ),
                ),
            ],
            options={
                "verbose_name": "Our Rates Settings",
                "verbose_name_plural": "Our Rates Settings",
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "title"],
            },
        ),
        migrations.DeleteModel(
            name="BecomeDealerSection",
        ),
        migrations.AddField(
            model_name="contactenquiry",
            name="enquiry_type",
            field=models.CharField(
                choices=[
                    ("jewellery", "Jewellery"),
                    ("gold_bullion", "Gold Bullion"),
                    ("silver_bullion", "Silver Bullion"),
                    ("bulk_order", "Bulk Order"),
                ],
                default="jewellery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hallmark",
            field=models.CharField(
                blank=True, help_text="e.g. BIS Hallmarked", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="making_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="metal_type",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("diamond", "Diamond"),
                    ("platinum", "Platinum"),
                    ("other", "Other"),
                ],
                default="gold",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purity",
            field=models.CharField(
                blank=True, help_text="e.g. 22K, 24K, 999", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_gold995",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_gold999_gst_buy",
            field=models.FloatField(default=1.01),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_gold999_gst_sell",
            field=models.FloatField(default=1.016),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_gold_future_buy",
            field=models.FloatField(default=0.99),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_gold_future_sell",
            field=models.FloatField(default=0.995),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_silver_chorsa",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_silver_future_buy",
            field=models.FloatField(default=1.06),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_silver_future_sell",
            field=models.FloatField(default=1.06),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="factor_silver_kacchi",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_buy_formula_operator",
            field=models.CharField(
                choices=[
                    ("+", "Addition (+)"),
                    ("-", "Subtraction (-)"),
                    ("*", "Multiply (*)"),
                    ("/", "Divide (/)"),
                    ("%", "Percentage Markup (%)"),
                ],
                default="+",
                help_text="Formula applied to the displayed 10 gm Gold market rate for dealer buy.",
                max_length=1,
                verbose_name="Gold buy formula",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_buy_formula_value",
            field=models.FloatField(
                default=0.0,
                help_text="Value used by the Gold dealer buy formula.",
                verbose_name="Gold buy formula value",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_buy_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_display_multiplier",
            field=models.FloatField(
                default=1.0,
                help_text="Convert API gold gram price to display unit. Use 1 for gram rate.",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_formula_operator",
            field=models.CharField(
                choices=[
                    ("+", "Addition (+)"),
                    ("-", "Subtraction (-)"),
                    ("*", "Multiply (*)"),
                    ("/", "Divide (/)"),
                    ("%", "Percentage Markup (%)"),
                ],
                default="+",
                help_text="Formula applied to the displayed 10 gm Gold market rate for dealer sell.",
                max_length=1,
                verbose_name="Gold sell formula",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_formula_value",
            field=models.FloatField(
                default=0.0,
                help_text="Value used by the Gold dealer sell formula.",
                verbose_name="Gold sell formula value",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_sell_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_spread_pct",
            field=models.FloatField(
                default=0.16, help_text="Hybrid mode: gold buy/sell spread percent."
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="our_gold_buy_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="our_gold_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="our_gold_sell_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="our_silver_buy_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="our_silver_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="our_silver_sell_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="rate_last_updated",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="rate_source_mode",
            field=models.CharField(
                choices=[
                    ("api", "API Live Rates"),
                    ("manual", "Manual Admin Rates"),
                    ("hybrid", "Hybrid (API + Admin Tuning)"),
                ],
                default="api",
                help_text="Choose whether live rates come from API or manual admin values.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold995_buy",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold995_high",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold995_low",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold995_sell",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold999gst_buy",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold999gst_high",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold999gst_low",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_gold999gst_sell",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_goldfuture_buy",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_goldfuture_high",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_goldfuture_low",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_goldfuture_sell",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_chorsa_buy",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_chorsa_high",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_chorsa_low",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_chorsa_sell",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_kacchi_buy",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_kacchi_high",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_kacchi_low",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silver_kacchi_sell",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silverfuture_buy",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silverfuture_high",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silverfuture_low",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="row_silverfuture_sell",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_buy_formula_operator",
            field=models.CharField(
                choices=[
                    ("+", "Addition (+)"),
                    ("-", "Subtraction (-)"),
                    ("*", "Multiply (*)"),
                    ("/", "Divide (/)"),
                    ("%", "Percentage Markup (%)"),
                ],
                default="+",
                help_text="Formula applied to the displayed 10 gm Silver market rate for dealer buy.",
                max_length=1,
                verbose_name="Silver buy formula",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_buy_formula_value",
            field=models.FloatField(
                default=0.0,
                help_text="Value used by the Silver dealer buy formula.",
                verbose_name="Silver buy formula value",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_buy_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_display_multiplier",
            field=models.FloatField(
                default=1.0,
                help_text="Convert API silver gram price to display unit. Use 1 for gram rate.",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_formula_operator",
            field=models.CharField(
                choices=[
                    ("+", "Addition (+)"),
                    ("-", "Subtraction (-)"),
                    ("*", "Multiply (*)"),
                    ("/", "Divide (/)"),
                    ("%", "Percentage Markup (%)"),
                ],
                default="+",
                help_text="Formula applied to the displayed 10 gm Silver market rate for dealer sell.",
                max_length=1,
                verbose_name="Silver sell formula",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_formula_value",
            field=models.FloatField(
                default=0.0,
                help_text="Value used by the Silver dealer sell formula.",
                verbose_name="Silver sell formula value",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_sell_rate",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_spread_pct",
            field=models.FloatField(
                default=0.59, help_text="Hybrid mode: silver buy/sell spread percent."
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="spread_pct",
            field=models.FloatField(
                default=0.5,
                help_text="Legacy/common spread percent (used if metal-specific spreads are empty).",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="use_exact_table_rates",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, table rows use exact admin values below.",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="communitygallery",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="communitysection",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contactenquiry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pageheader",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pageheader",
            name="page",
            field=models.CharField(
                choices=[
                    ("about", "About Page"),
                    ("contact", "Contact Page"),
                    ("shop", "Products Page"),
                    ("bullion_rates", "Live Rates Page"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_details",
            field=models.TextField(
                blank=True, default="Shipping available all over India"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storelocation",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_name",
            field=models.CharField(default="Shree Rudra Bullion", max_length=200),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="website.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="website.productsubcategory",
            ),
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
