# Generated by Django 5.2.8 on 2026-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_ourratessettings_productsubcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="gold_9950_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_9950_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_9950_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_9950_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_999_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_999_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_999_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_999_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_rtgs_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_rtgs_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_rtgs_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_rtgs_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_chorsa_99_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_chorsa_99_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_chorsa_99_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_chorsa_99_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_kacchi_50_90_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_kacchi_50_90_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_kacchi_50_90_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_kacchi_50_90_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_rtgs_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_rtgs_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_rtgs_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_rtgs_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_tukda_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_tukda_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_tukda_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_tukda_sell_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_rtgs_buy_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_rtgs_buy_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_rtgs_sell_operator",
            field=models.CharField(
                choices=[("+", "Addition (+)"), ("-", "Subtraction (-)")],
                default="+",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_rtgs_sell_value",
            field=models.FloatField(default=0.0),
        ),
    ]
