# Generated by Django 5.2.8 on 2026-05-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_websitesettings_gold_9950_buy_operator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveRateSettings",
            fields=[],
            options={
                "verbose_name": "Live Rate Adjustment",
                "verbose_name_plural": "Live Rate Adjustments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("website.websitesettings",),
        ),
    ]
