# Generated by Django 5.2.8 on 2026-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_liveratesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="footer_phone_1",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Footer phone 1"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="footer_phone_2",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Footer phone 2"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="footer_phone_3",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Footer phone 3"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="footer_phone_4",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Footer phone 4"
            ),
        ),
    ]
