# Generated by Django 5.2.8 on 2026-05-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_websitesettings_footer_phone_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="gold_9950_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_999_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="gold_rtgs_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_chorsa_99_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_kacchi_50_90_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_rtgs_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_peti_tukda_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="silver_rtgs_is_active",
            field=models.BooleanField(default=True),
        ),
    ]
