# Generated by Django 5.2.8 on 2026-05-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_websitesettings_gold_9950_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSignupRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "App Signup Request",
                "verbose_name_plural": "App Signup Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
