# Generated by Django 5.2.8 on 2026-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_appsignuprequest_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsignuprequest",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="app_profiles/"),
        ),
    ]
