# Generated by Django 5.2.8 on 2026-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_appprofileupdaterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="goldrates_cloud_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Update this key from admin when GoldRates Cloud provides a new API key.",
                max_length=100,
                verbose_name="GoldRates Cloud API key",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="goldrates_cloud_api_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="GoldRates Cloud live-rate endpoint. Leave blank to use the server default.",
                verbose_name="GoldRates Cloud API URL",
            ),
        ),
    ]
